name       : haskell-hourglass
version    : 0.2.12
release    : 3
source     :
    - https://hackage.haskell.org/package/hourglass-0.2.12/hourglass-0.2.12.tar.gz : 44335b5c402e80c60f1db6a74462be4ea29d1a9043aa994334ffee1164f1ca4a
license    : BSD-3-Clause
component  : programming.haskell
summary    : Simple time library focusing on simple but powerful and performant API
description: |
    Simple time library focusing on simple but powerful and performant API
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
