name       : haskell-hourglass
version    : 0.2.10
release    : 1
source     :
    - http://hackage.haskell.org/package/hourglass-0.2.10/hourglass-0.2.10.tar.gz : d553362d7a6f7df60d8ff99304aaad0995be81f9d302725ebe9441829a0f8d80
license    : BSD-3-Clause
component  : programming.haskell
summary    : Simple time library focusing on simple but powerful and performant API
description: |
    Simple time library focusing on simple but powerful and performant API
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
