name       : haskell-hourglass
version    : 0.2.11
release    : 2
source     :
    - https://hackage.haskell.org/package/hourglass-0.2.11/hourglass-0.2.11.tar.gz : 18a6bb303fc055275cca45aaffc17b6a04b2e9d7509aa5aa5bb9d9239f4e4f51
license    : BSD-3-Clause
component  : programming.haskell
summary    : Simple time library focusing on simple but powerful and performant API
description: |
    Simple time library focusing on simple but powerful and performant API
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
